@echo off
echo Starting AI-Powered Internal Docs Assistant...
echo.
echo Killing any existing Python processes...
taskkill /f /im python.exe 2>nul
echo Starting fresh server...
python ai_chatbot.py
pause